checkpoint:
  chkpt_saving_period: 1
  directory          : ../train/experiments/chkpts
  filename_prefix    : fsdp
  path_chkpt_prev    : null
  pretrain           : null
dataset:
  batch_size     : 2
  num_workers    : 2
  path_predict   : dataset.json
  seg_size       : 20
  server_address : [localhost, 5000]
  transforms:
    norm:
      Rayonix:
        mean: 116.92
        std: 22.89
      epix10k2M:
        mean: 46.6
        std: 98.3
      jungfrau4M:
        mean: 593.17
        std: 204.13
    H_pad: 2048
    W_pad: 2048
    num_patch: 100
    size_patch: 20
    angle_max: 360
    frac_shift_max: 0.1
    downscale_factors: [2, 2]
    var_size_patch: 0.2
    patch_size: 224
    stride: 224
dist:
  backend               : nccl
  uses_unique_world_seed: true
  dtype                 : float16
logging:
  directory      : predictions/logs
  filename_prefix: fsdp
misc:
  num_gpus            : 4
  num_nodes           : 4
  uses_mixed_precision: true
  compiles_model      : false
  data_dump_on        : false
model:
  name: 'facebook/vit-mae-base'
predictions:
  save_filepath : predictions/outputs
  save_tensor : true
  save_img : true
