defaults:
  - _self_
  - bsub_config : base
  - predict_config: base

auto_submit: false
job: my_job

path:
  dir_bsub_template  : 'hydra_config/bsub_config'
  file_bsub_template : 'template.bsub'
  dir_bsub_jobs      : 'predictions/bsub'
  dir_yaml_jobs      : 'predictions/yaml'
  file_bsub_job      : 'base.bsub'
  file_yaml_job      : 'base.yaml'

hydra:
  run:
    dir: 'predictions/hydra/'
